# Generated by Django 3.0.8 on 2020-07-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signUp',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('passp', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
