# Generated by Django 3.0.8 on 2020-07-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20200723_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='img',
            field=models.ImageField(default='', upload_to='log/images/'),
        ),
    ]
