# Generated by Django 3.0.8 on 2020-07-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20200723_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='img',
            field=models.ImageField(default='', upload_to='log/images'),
        ),
    ]
